#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:

# INFO: Version Number 900 for example is 9.0.0 or 9110 would be 9.1.10 

    - name: Cloning PG Blitz v9
      git:
        repo: "https://github.com/PGBlitz/PGBlitz.com"
        dest: /opt/plexguide
        version: "900"
        force: yes
